"""Add ON DELETE CASCADE

Revision ID: 3f0e08e708e2
Revises: abe8396e8871
Create Date: 2024-06-12 16:43:21.472535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0e08e708e2'
down_revision = 'abe8396e8871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_id_cover_covers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_id_cover_covers'), 'covers', ['id_cover'], ['id_cover'], ondelete='CASCADE')

    with op.batch_alter_table('connect_genre_book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_connect_genre_book_id_book_books', type_='foreignkey')
        batch_op.drop_constraint('fk_connect_genre_book_id_genre_genres', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_connect_genre_book_id_book_books'), 'books', ['id_book'], ['id_book'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_connect_genre_book_id_genre_genres'), 'genres', ['id_genre'], ['id_genre'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_id_book_books', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_id_user_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_id_user_users'), 'users', ['id_user'], ['id_user'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_id_book_books'), 'books', ['id_book'], ['id_book'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_id_role_roles', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_id_role_roles'), 'roles', ['id_role'], ['id_role'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_id_role_roles'), type_='foreignkey')
        batch_op.create_foreign_key('fk_users_id_role_roles', 'roles', ['id_role'], ['id_role'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_id_book_books'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_id_user_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_id_user_users', 'users', ['id_user'], ['id_user'])
        batch_op.create_foreign_key('fk_reviews_id_book_books', 'books', ['id_book'], ['id_book'])

    with op.batch_alter_table('connect_genre_book', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_connect_genre_book_id_genre_genres'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_connect_genre_book_id_book_books'), type_='foreignkey')
        batch_op.create_foreign_key('fk_connect_genre_book_id_genre_genres', 'genres', ['id_genre'], ['id_genre'])
        batch_op.create_foreign_key('fk_connect_genre_book_id_book_books', 'books', ['id_book'], ['id_book'])

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_id_cover_covers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_books_id_cover_covers', 'covers', ['id_cover'], ['id_cover'])

    # ### end Alembic commands ###
