"""Initial migration

Revision ID: abe8396e8871
Revises: 
Create Date: 2024-06-10 15:47:57.860711

"""
from alembic import op
import sqlalchemy as sa
import hashlib
from models import Users
from sqlalchemy import func
import datetime

user = Users()


# revision identifiers, used by Alembic.
revision = 'abe8396e8871'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covers',
    sa.Column('id_cover', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('mimetype', sa.String(length=128), nullable=False),
    sa.Column('md5_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id_cover', name=op.f('pk_covers')),
    sa.UniqueConstraint('md5_hash', name=op.f('uq_covers_md5_hash'))
    )
    op.create_table('genres',
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.Column('name_genre', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_genre', name=op.f('pk_genres'))
    )
    op.create_table('roles',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('name_role', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_role', name=op.f('pk_roles'))
    )
    op.create_table('books',
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('name_book', sa.String(length=128), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.String(length=128), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('id_cover', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cover'], ['covers.id_cover'], name=op.f('fk_books_id_cover_covers')),
    sa.PrimaryKeyConstraint('id_book', name=op.f('pk_books'))
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lastname', sa.String(length=128), nullable=False),
    sa.Column('middlename', sa.String(length=128), nullable=True),
    sa.Column('login', sa.String(length=32), nullable=False),
    sa.Column('hash_pass', sa.String(length=256), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id_role'], name=op.f('fk_users_id_role_roles')),
    sa.PrimaryKeyConstraint('id_user', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('connect_genre_book',
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['books.id_book'], name=op.f('fk_connect_genre_book_id_book_books')),
    sa.ForeignKeyConstraint(['id_genre'], ['genres.id_genre'], name=op.f('fk_connect_genre_book_id_genre_genres')),
    sa.PrimaryKeyConstraint('id_book', 'id_genre', name=op.f('pk_connect_genre_book'))
    )
    op.create_table('reviews',
    sa.Column('id_review', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['books.id_book'], name=op.f('fk_reviews_id_book_books')),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], name=op.f('fk_reviews_id_user_users')),
    sa.PrimaryKeyConstraint('id_review', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###
    data_upgrades()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('connect_genre_book')
    op.drop_table('users')
    op.drop_table('books')
    op.drop_table('roles')
    op.drop_table('genres')
    op.drop_table('covers')
    # ### end Alembic commands ###


def md5_hash(value):
    return hashlib.md5(value.encode()).hexdigest()


def data_upgrades():

    covers_table = sa.table('covers',
                            sa.column('id_cover', sa.Integer),
                            sa.column('filename', sa.String),
                            sa.column('mimetype', sa.String),
                            sa.column('md5_hash', sa.String))
    genres_table = sa.table('genres',
                            sa.column('id_genre', sa.Integer),
                            sa.column('name_genre', sa.String))
    roles_table = sa.table('roles',
                           sa.column('id_role', sa.Integer),
                           sa.column('name_role', sa.String),
                           sa.column('description', sa.Text))
    books_table = sa.table('books',
                           sa.column('id_book', sa.Integer),
                           sa.column('name_book', sa.String),
                           sa.column('short_description', sa.Text),
                           sa.column('year', sa.Integer),
                           sa.column('publisher', sa.String),
                           sa.column('author', sa.String),
                           sa.column('pages', sa.Integer),
                           sa.column('id_cover', sa.Integer))
    connect_genre_book_table = sa.table('connect_genre_book',
                            sa.column('id_book', sa.Integer),
                            sa.column('id_genre', sa.Integer))
    reviews_table = sa.table('reviews',
                           sa.column('id_review', sa.Integer),
                           sa.column('rating', sa.Integer),
                           sa.column('text', sa.Text),
                           sa.column('created_at', sa.DateTime),
                           sa.column('id_book', sa.Integer),
                           sa.column('id_user', sa.Integer))
    op.bulk_insert(covers_table,
        [
            {'id_cover': 1, 'filename': '1', 'mimetype': 'jpg', 'md5_hash': md5_hash('1')},
            {'id_cover': 2, 'filename': '2', 'mimetype': 'jpg', 'md5_hash': md5_hash('2')},
            {'id_cover': 3, 'filename': '3', 'mimetype': 'jpg', 'md5_hash': md5_hash('3')},
            {'id_cover': 4, 'filename': '4', 'mimetype': 'jpg', 'md5_hash': md5_hash('4')},
            {'id_cover': 5, 'filename': '5', 'mimetype': 'jpg', 'md5_hash': md5_hash('5')},
            {'id_cover': 6, 'filename': '6', 'mimetype': 'jpg', 'md5_hash': md5_hash('6')},
            {'id_cover': 7, 'filename': '7', 'mimetype': 'jpg', 'md5_hash': md5_hash('7')},
            {'id_cover': 8, 'filename': '8', 'mimetype': 'jpg', 'md5_hash': md5_hash('8')},
            {'id_cover': 9, 'filename': '9', 'mimetype': 'jpg', 'md5_hash': md5_hash('9')},
            {'id_cover': 10, 'filename': '10', 'mimetype': 'jpg', 'md5_hash': md5_hash('10')},
            {'id_cover': 11, 'filename': '11', 'mimetype': 'jpg', 'md5_hash': md5_hash('11')},
            {'id_cover': 12, 'filename': '12', 'mimetype': 'jpg', 'md5_hash': md5_hash('12')},
            {'id_cover': 13, 'filename': '13', 'mimetype': 'jpg', 'md5_hash': md5_hash('13')},
            {'id_cover': 14, 'filename': '14', 'mimetype': 'jpg', 'md5_hash': md5_hash('14')},
            {'id_cover': 15, 'filename': '15', 'mimetype': 'jpg', 'md5_hash': md5_hash('15')},
            {'id_cover': 16, 'filename': '16', 'mimetype': 'jpg', 'md5_hash': md5_hash('16')},
            {'id_cover': 17, 'filename': '17', 'mimetype': 'jpg', 'md5_hash': md5_hash('17')},
            {'id_cover': 18, 'filename': '18', 'mimetype': 'jpg', 'md5_hash': md5_hash('18')},
            {'id_cover': 19, 'filename': '19', 'mimetype': 'jpg', 'md5_hash': md5_hash('19')},
            {'id_cover': 20, 'filename': '20', 'mimetype': 'jpg', 'md5_hash': md5_hash('20')},
            {'id_cover': 21, 'filename': '21', 'mimetype': 'jpg', 'md5_hash': md5_hash('21')},
            {'id_cover': 22, 'filename': '22', 'mimetype': 'jpg', 'md5_hash': md5_hash('22')},
            {'id_cover': 23, 'filename': '23', 'mimetype': 'jpg', 'md5_hash': md5_hash('23')},
            {'id_cover': 24, 'filename': '24', 'mimetype': 'jpg', 'md5_hash': md5_hash('24')},
            {'id_cover': 25, 'filename': '25', 'mimetype': 'jpg', 'md5_hash': md5_hash('25')},
            {'id_cover': 26, 'filename': '26', 'mimetype': 'jpg', 'md5_hash': md5_hash('26')},
            {'id_cover': 27, 'filename': '27', 'mimetype': 'jpg', 'md5_hash': md5_hash('27')},
            {'id_cover': 28, 'filename': '28', 'mimetype': 'jpg', 'md5_hash': md5_hash('28')},
            {'id_cover': 29, 'filename': '29', 'mimetype': 'jpg', 'md5_hash': md5_hash('29')},
            {'id_cover': 30, 'filename': '30', 'mimetype': 'jpg', 'md5_hash': md5_hash('30')},
        ])
    op.bulk_insert(genres_table,
        [
            {'id_genre': 1, 'name_genre': 'Фантастика'},
            {'id_genre': 2, 'name_genre': 'Фэнтези'},
            {'id_genre': 3, 'name_genre': 'Детективы'},
            {'id_genre': 4, 'name_genre': 'Романы'},
            {'id_genre': 5, 'name_genre': 'Исторические'},
            {'id_genre': 6, 'name_genre': 'Биография и мемуары'},
            {'id_genre': 7, 'name_genre': 'Научная литература'},
            {'id_genre': 8, 'name_genre': 'Саморазвитие и мотивация'},
            {'id_genre': 9, 'name_genre': 'Психология'},
            {'id_genre': 10, 'name_genre': 'Приключение'},
            {'id_genre': 11, 'name_genre': 'Ужасы и мистика'},
            {'id_genre': 12, 'name_genre': 'Кулинарные книги'},
            {'id_genre': 13, 'name_genre': 'Искусство и культура'},
            {'id_genre': 14, 'name_genre': 'Поэзия и драматургия'},
            {'id_genre': 15, 'name_genre': 'Детская литература'},
        ])
    op.bulk_insert(roles_table,
        [
            {'id_role': 1, 'name_role': 'Администратор', 'description': 'Суперпользователь, имеет полный доступ к системе, \
             в том числе к созданию и удалению книг'},
            {'id_role': 2, 'name_role': 'Модератор', 'description': 'Может редактировать данные книг и производить модерацию рецензий'},
            {'id_role': 3, 'name_role': 'Пользователь', 'description': 'Может оставлять рецензии'},
        ])
    op.bulk_insert(books_table,
        [
            {'id_book': 1, 'name_book': 'Первому игроку приготовиться', 'short_description': 'В 2045 году реальный мир – не самое приятное \
             место. По-настоящему живым Уэйд Уоттс чувствует себя лишь в OASISе – огромном виртуальном пространстве, где проводит свои дни \
             большая часть человечества. Перед смертью эксцентричный создатель OASISа, одержимый по-культурой прошлих лет, составляет на ее \
             основе ряд сложнейших головоломок. Тот, кто разгадает их первым, унаследует его огромное состояние – и контроль над самим OASISом.', 
             'year': 2011, 'publisher': 'Литературный ветер', 'author': 'Эрнест Клайн', 'pages': 443, 'id_cover': 1},
            {'id_book': 2, 'name_book': 'Автостопом по галактике', 'short_description': 'Дом главного героя Артура Дента пытаются снести для \
             постройки новой автодороги. Чтобы остановить снос, Артур ложится перед бульдозером, после чего прибывает его друг Форд Префект. \
             Форд рассказывает Артуру, что является пришельцем из окрестностей Бетельгейзе и что планету Земля планируют уничтожить для \
             постройки гиперпространственной магистрали.', 
             'year': 1985, 'publisher': 'Золотое перо', 'author': 'Дуглас Адамс', 'pages': 240, 'id_cover': 2},
            {'id_book': 3, 'name_book': 'Пламя и кровь', 'short_description': 'Тирион Ланнистер еще не стал заложником жестокого рока, Бран \
             Старк еще не сделался калекой, а голова его отца Неда Старка еще не скатилась с эшафота. Ни один человек в Королевствах не смеет \
             даже предположить, что Дейенерис Таргариен когда-нибудь назовут Матерью Драконов. Вестерос не привел к покорности соседние \
             государства, и Железный Трон, который, согласно поговорке, ковался в крови и пламени, далеко еще не насытился.', 
             'year': 2018, 'publisher': 'Тихий шелест', 'author': 'Джордж Мартин', 'pages': 380, 'id_cover': 3},
            {'id_book': 4, 'name_book': 'Танец с драконами', 'short_description': '«Танцем драконов» издавна звали в Семи Королевствах войну. \
             Но теперь война охватывает все новые и новые земли. Война катится с Севера – из-за Стены. Война идет с Запада – с Островов.\
             Войну замышляет Юг, мечтающий посадить на Железный Трон свою ставленницу. И совсем уже неожиданную угрозу несет с Востока \
             вошедшая в силу «мать драконов» Дейенерис…', 
             'year': 2011, 'publisher': 'Звездная поляна', 'author': 'Джордж Мартин', 'pages': 598, 'id_cover': 4},
            {'id_book': 5, 'name_book': 'Этюд в багровых тонах', 'short_description': 'Врач снимает квартиру вместе с частным сыщиком. \
             Расследуя вместе с ним преступление, доктор ведёт дневник, из которого публика узнаёт о сыщике Шерлоке Холмсе.', 
             'year': 1887, 'publisher': 'Лесные сказки', 'author': 'Артур Конан Дойл', 'pages': 151, 'id_cover': 5},
            {'id_book': 6, 'name_book': 'Собака Баскервилей', 'short_description': 'По преданию, род Баскервилей с XVII века преследует \
             чудовищная собака. Когда сэр Чарльз Баскервиль умирает при загадочных обстоятельствах, а рядом с телом находят собачьи следы, \
             расследовать это дело берутся знаменитый сыщик Шерлок Холмс и его друг доктор Уотсон. Им предстоит схватка с дерзким и опасным \
             противником, не уступающим Холмсу в изобретательности.', 
             'year': 1902, 'publisher': 'Морские глубины', 'author': 'Артур Конан Дойл', 'pages': 190, 'id_cover': 6},
            {'id_book': 7, 'name_book': 'Мы', 'short_description': '. Роман об «обществе равных», в котором человеческая личность сведена \
             к «нумеру». В нем унифицировано все – одежда и квартиры, мысли и чувства. Нет ни семьи, ни прочных привязанностей…', 
             'year': 1920, 'publisher': 'Солнечная стрела', 'author': 'Е. И. Замятин', 'pages': 181, 'id_cover': 7},
            {'id_book': 8, 'name_book': 'Мастер и Маргарита', 'short_description': 'Жарким майским вечером председатель правления МАССОЛИТ \
             Михаил Берлиоз и молодой поэт Иван Бездомный отправились на Патриаршие пруды, чтобы обсудить: существовал ли Иисус Христос. \
             Беседой литераторов заинтересовался некий импозантный гражданин-иностранец. Профессор Воланд стал уверять новых знакомых, \
             что лично присутствовал на допросе бродяги Иешуа Га-Ноцри, который проводил Понтий Пилат.', 
             'year': 1967, 'publisher': 'Вечерние огни', 'author': 'М. А. Булгаков', 'pages': 470, 'id_cover': 8},
            {'id_book': 9, 'name_book': 'Железный король', 'short_description': ' Великий магистр ордена тамплиеров Жак де Моле, взойдя \
             на костер 18 марта 1314 года, проклял своих палачей – папу Климента V, короля Филиппа Красивого, его советника Гийома де \
             Ногаре и все их помство до тринадцатого колена. Первый удар судьбы – обвинение невесток короля в неверности – не замедлил \
             последовать. Но еще никто не знает, какие беды сулит будущее Железному королю…', 
             'year': 1955, 'publisher': 'Небесная книга', 'author': 'Морис Дрюон', 'pages': 350, 'id_cover': 9},
            {'id_book': 10, 'name_book': 'Чингисхан', 'short_description': 'Это яркое историческое произведение, раскрывающее перед \
             читателем само становление экспансионистской программы ордынского правителя, показывающее сложную подготовку хана-завоевателя \
             к решающим схваткам с одним из зрелых феодальных организмов Средней Азии – Хорезмом, создающее широкую картину захвата и \
             разорения Хорезмийского государства полчищами Чингиз-хана. ', 
             'year': 1939, 'publisher': 'Серебрянный Лист', 'author': 'В. Г. Ян', 'pages': 400, 'id_cover': 10},
            {'id_book': 11, 'name_book': 'Жажда жизни', 'short_description': 'Биографический роман Ирвинга Стоуна 1934 года о жизни \
             голландского художника Винсента ван Гога и его невзгодах.', 
             'year': 1934, 'publisher': 'Морские глубины', 'author': 'Ирвинг Стоун', 'pages': 640, 'id_cover': 11},
            {'id_book': 12, 'name_book': 'Почти серьезно', 'short_description': 'Правдивая и тонкая биография заслуженного артиста СССР Юрия Никулина!', 
             'year': 1976, 'publisher': 'Солнечная стрела', 'author': 'Юрий Никулин', 'pages': 784, 'id_cover': 12},
            {'id_book': 13, 'name_book': 'Краткая история времени', 'short_description': ' В этой книге автор пытается ответить на самые \
             сложные и интригующие вопросы о мироздании: когда и почему началась Вселенная? безгранична ли Вселенная или у нее есть \
             предел? всегда ли время текло вдоль привычного для нас вектора? возможны ли путешествия во времени? что ожидает космос в далеком будущем?', 
             'year': 1988, 'publisher': 'Золотое перо', 'author': 'Стивен Хокинг', 'pages': 320, 'id_cover': 13},
            {'id_book': 14, 'name_book': 'Теория всего', 'short_description': 'Книга объединяет семь лекций, охватывающих широкий \
             диапазон тем: от Большого взрыва и черных дыр до теории струн. Автор описывает представления о Вселенной – от постулата \
             о том, что Земля имеет форму шара, до теории о расширении Вселенной, основанной на недавних наблюдениях.', 
             'year': 2006, 'publisher': 'Литературный ветер', 'author': 'Стивен Хокинг', 'pages': 149, 'id_cover': 14},
            {'id_book': 15, 'name_book': 'Важные годы. Почему не стоит откладывать жизнь на потом', 'short_description': 'Эта книга о \
             десятилетии, определяющем судьбу человека. Инвестиции, сделанные в этот период в собственное развитие во всех сферах жизни, \
             принесут максимальную отдачу. Автор объясняет, почему не стоит откладывать начало взрослой жизни на потом, и рассказывает, что \
             нужно делать в это время жизни человека.', 
             'year': 2012, 'publisher': 'Вечерние огни', 'author': 'Мэг Джей', 'pages': 271, 'id_cover': 15},
            {'id_book': 16, 'name_book': 'НИ СЫ. Иди вперед и ничего не бойся', 'short_description': 'Хочешь жить так, как никогда не жил - \
             начни делать то, что никогда не делал. Главная формула саморазвития, которую можно свести к "восточной мудрости" - НИ СЫ.', 
             'year': 2020, 'publisher': 'Серебрянный Лист', 'author': 'Джен Синсеро', 'pages': 304, 'id_cover': 16},
            {'id_book': 17, 'name_book': 'Чертоги разума', 'short_description': '«Чертоги разума» – научно-популярная книга Андрея Курпатова, \
             полностью посвященная работе мозга и эффективным практикам улучшения качества жизни.', 
             'year': 2018, 'publisher': 'Звездная поляна', 'author': 'Андрей Курпатов', 'pages': 330, 'id_cover': 17},
            {'id_book': 18, 'name_book': 'Свобода от тревоги. Справиться с тревогой, пока она не расправилась с тобой', 'short_description': 'Из \
             этой книги вы узнаете, как обмануть свой страх и научиться справляться со стрессом. Здесь вы найдете простое пошаговое руководство, \
             чтобы преодолеть любые виды беспокойства. Теперь вы навсегда избавитесь от тревоги и начнете жить полной жизнью.', 
             'year': 2009, 'publisher': 'Лесные сказки', 'author': 'Роберт Лихи', 'pages': 447, 'id_cover': 18},
            {'id_book': 19, 'name_book': 'Таинственный остров', 'short_description': 'Во времена гражданской войны в США пятеро смельчаков-северян \
             спасаются от плена на воздушном шаре. Страшная буря выбрасывает их на берег необитаемого острова. Отвага и таланты новых поселенцев\
              острова помогают им обустроить свою жизнь, не испытывая нужды ни в еде, ни в одежде, ни в тепле и уюте. Мирное пребывание «робинзонов» \
             на острове нарушает угроза нападения пиратов, но какая-то таинственная сила помогает им в самых сложных ситуациях.', 
             'year': 1875, 'publisher': 'Тихий шелест', 'author': 'Жюль Верн', 'pages': 650, 'id_cover': 19},
            {'id_book': 20, 'name_book': 'Зов предков', 'short_description': 'Подчиняясь «зову предков», домашний пес Бэк одичал и ушел в волчью \
             стаю… Тысячи людей, томимые жаждой наживы, которая пробуждает зов первобытной дикости, устремились в живописный Клондайкский край \
             – неизвестный и загадочный мир Севера, суровых испытаний и золота!', 
             'year': 1903, 'publisher': 'Небесная Книга', 'author': 'Джек Лондон', 'pages': 110, 'id_cover': 20},
            {'id_book': 21, 'name_book': 'Сияние', 'short_description': 'Бывший преподаватель Джек Торранс устраивается зимним сторожем в горный \
             отель «Оверлук» и переезжает в него со своими женой и сыном. Будучи изолированным от внешнего мира, Джек испытывает постоянное влияние \
             тёмной сущности отеля и призраков, обитающих в его стенах.', 
             'year': 1977, 'publisher': 'Тихий шелест', 'author': 'Стивен Кинг', 'pages': 620, 'id_cover': 21},
            {'id_book': 22, 'name_book': 'Кладбище домашних животных', 'short_description': 'Казалось бы, семейство Крид - это настоящее воплощение \
             "американской мечты": отец - преуспевающий врач, красавица мать, прелестные дети. Для полной идиллии им не хватает лишь большого \
             старинного дома, куда они вскоре и переезжают. Но идиллия вдруг стала превращаться в кошмар. Потому что в окружающих их новое жилище \
             вековых лесах скрывается НЕЧТО, более ужасное, чем сама смерть и… более могущественное.', 
             'year': 1983, 'publisher': 'Небесная книга', 'author': 'Стивен Кинг', 'pages': 480, 'id_cover': 22},
            {'id_book': 23, 'name_book': 'Абсент', 'short_description': 'Книга известного английского культуролога Фила Бейкера рассказывает удивительную\
              историю абсента от времен Древней Греции и Рима до наших дней.', 
             'year': 2002, 'publisher': 'Золотое перо', 'author': 'Фил Бейкер', 'pages': 288, 'id_cover': 23},
            {'id_book': 24, 'name_book': 'Вино. Практический путеводитель', 'short_description': 'Идеальный бумажный путеводитель по вину для эпохи \
             цифровых технологий. Ясный, живой, без излишней заумности.', 
             'year': 2015, 'publisher': 'Солнечная стрела', 'author': 'Джастин Хэммек', 'pages': 234, 'id_cover': 24},
            {'id_book': 25, 'name_book': 'Искусство видеть', 'short_description': 'На примере общеизвестных произведений изобразительного искусства\
              и типичных рекламных изображений Бергер показывает, что наряду с непосредственным сообщением практически каждая картина, каждый \
              визуальный объект массовой культуры несёт в себе идеологический заряд, обусловленный интересами доминирующего класса или же доминирующего пола.', 
             'year': 1972, 'publisher': 'Литературный ветер', 'author': 'Джон Бергер', 'pages': 216, 'id_cover': 25},
            {'id_book': 26, 'name_book': 'Япония. Введение в искусство и кульутуру', 'short_description': 'Гора Фудзи, лепестки сакуры, роботы, \
             аниме и манга – Япония ассоциируется с целым набором образов. Но несмотря на то, что японская культура активно проникает на запад, \
             эта страна продолжает оставаться загадочной и непознанной. Эта книга познакомит вас со Страной восходящего солнца, расскажет об \
             истории и религии, искусстве и культурном влиянии на другие страны.', 
             'year': 2019, 'publisher': 'Звездная поляна', 'author': 'Анна Пушакова', 'pages': 165, 'id_cover': 26},
            {'id_book': 27, 'name_book': 'Комедии', 'short_description': 'В книге представлены четыре комедии величайшего английского писателя Уильяма \
             Шекспира: «Сон в летнюю ночь», «Много шума из ничего», «Как вам это понравится» и «Двенадцатая ночь». Комедии Шекспира восхищают нас \
             живостью, остроумием и искрящимся весельем, энергичностью, находчивостью и оптимизмом героев.', 
             'year': 2017, 'publisher': 'Вечерние огни', 'author': 'Уильям Шекспир', 'pages': 309, 'id_cover': 27},
            {'id_book': 28, 'name_book': 'Трагедии', 'short_description': 'Издание выпущено в 1954 году Государственным издательством Художественной \
             Литературы, Москва. Издательский переплет. Сохранность хорошая. В сборник вошли трагедии: "Эдип-царь", "Эдип в Колоне", "Антигона", "Трахинянки", "Аянт", "Филоктет".', 
             'year': 1988, 'publisher': 'Морские глубины', 'author': 'Софокл', 'pages': 496, 'id_cover': 28},
            {'id_book': 29, 'name_book': 'Ёжик в тумане', 'short_description': 'Ёжик и Медвежонок - настоящие неразлучные друзья. Они ходят друг \
             к другу в гости, вместе сумерничают, читают стихи великих поэтов. Ёжик любит протирать звёзды, чтобы они не потускнели, а Медвежонок \
             водит знакомство с Солнечным зайцем и знает, как перехитрить время. ', 
             'year': 1972, 'publisher': 'Серебрянный Лист', 'author': 'С. С. Козлов', 'pages': 91, 'id_cover': 29},
            {'id_book': 30, 'name_book': 'Пеппи Длинныйчулок', 'short_description': 'Никого на свете нет сильнее Пеппи, она способна уложить на \
             лопатки даже самого прославленного силача. Но не только этим знаменита Пеппи. Ещё она самая весёлая, самая непредсказуемая, самая \
             озорная и самая добрая девочка в мире, с которой непременно хочется подружиться!', 
             'year': 1945, 'publisher': 'Лесные сказки', 'author': 'Астрид Линдгрен', 'pages': 326, 'id_cover': 30},
            
          
        ])
    op.bulk_insert(connect_genre_book_table,
        [
            {'id_book': 1, 'id_genre': 1},
            {'id_book': 1, 'id_genre': 4},
            {'id_book': 1, 'id_genre': 10},
            {'id_book': 2, 'id_genre': 1},
            {'id_book': 2, 'id_genre': 10},
            {'id_book': 3, 'id_genre': 2},
            {'id_book': 4, 'id_genre': 2},
            {'id_book': 5, 'id_genre': 3},
            {'id_book': 6, 'id_genre': 3},
            {'id_book': 7, 'id_genre': 4},
            {'id_book': 8, 'id_genre': 4},
            {'id_book': 8, 'id_genre': 2},
            {'id_book': 9, 'id_genre': 5},
            {'id_book': 9, 'id_genre': 4},
            {'id_book': 10, 'id_genre': 5},
            {'id_book': 11, 'id_genre': 6},
            {'id_book': 12, 'id_genre': 6},
            {'id_book': 13, 'id_genre': 7},
            {'id_book': 14, 'id_genre': 7},
            {'id_book': 15, 'id_genre': 8},
            {'id_book': 16, 'id_genre': 8},
            {'id_book': 17, 'id_genre': 9},
            {'id_book': 18, 'id_genre': 9},
            {'id_book': 19, 'id_genre': 10},
            {'id_book': 19, 'id_genre': 4},
            {'id_book': 20, 'id_genre': 10},
            {'id_book': 21, 'id_genre': 11},
            {'id_book': 21, 'id_genre': 2},
            {'id_book': 21, 'id_genre': 1},
            {'id_book': 22, 'id_genre': 11},
            {'id_book': 22, 'id_genre': 2},
            {'id_book': 22, 'id_genre': 1},
            {'id_book': 23, 'id_genre': 12},
            {'id_book': 24, 'id_genre': 12},
            {'id_book': 25, 'id_genre': 13},
            {'id_book': 26, 'id_genre': 13},
            {'id_book': 27, 'id_genre': 14},
            {'id_book': 28, 'id_genre': 14},
            {'id_book': 29, 'id_genre': 15},
            {'id_book': 30, 'id_genre': 15},
        ])
    op.bulk_insert(reviews_table,
        [
            {'id_review': 1, 'rating': 5, 'text': 'Полезная книга', 'created_at': datetime.datetime.now(), 'id_book': 1, 'id_user': 2},
            {'id_review': 2, 'rating': 4, 'text': 'Книга интригует', 'created_at': datetime.datetime.now(), 'id_book': 2, 'id_user': 4},
        ])
                              